#!/usr/bin/env bash
#
# deploy.sh — build, test, then publish airplane-watch.
#
# 🔴 THIS SCRIPT REFUSES TO RUN UNTIL THE SITE IS ACTUALLY READY TO GO LIVE, and
# that is the point rather than an annoyance. House standard parts 5c and 7a: on
# the day a site is deployed four things are made TOGETHER — the DNS record, the
# theme colour, the background, and its own Google Analytics property in the `mcp`
# account, named with the full domain. The unit suite contains a test that fails
# while `data-ga-id` is still the placeholder, so `npm test` fails and this script
# stops before anything is published. A half-deployed site is worse than an
# undeployed one.
#
# The static site goes to Caddy on dvs-sites; the /api proxy goes to the
# Cloudflare Worker. Both are needed: without the Worker the page loads and every
# poll fails.
#
# Usage: bash tools/deploy.sh [--dry-run]

set -euo pipefail

cd "$(dirname "$0")/.."
SITE_DIR="site"
REMOTE_DIR="/srv/airplane-watch"
HOST="airplane-watch.nodejavascript.com"
DRY_RUN="${1:-}"

say() { printf '\n\033[1;36m%s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31m%s\033[0m\n' "$*" >&2; exit 1; }

say "1/6 · build"
npm run build

say "2/6 · unit tests (this is where the GA-placeholder gate stops an early deploy)"
npm test

say "3/6 · check the pieces that must exist before a deploy"
[ -f "$SITE_DIR/index.html" ] || die "no $SITE_DIR/index.html"
[ -f "$SITE_DIR/consent.js" ] || die "no $SITE_DIR/consent.js — the gate did not build"
# 🔴 THE FAULT REPORTER IS LOAD-BEARING NOW: the cookie panel declares it as a Required
# row, so a page that shipped without it would be a panel describing something that is
# not there. `site/faults.js` is generated by tsc from `src/faults.ts` like the other two.
[ -f "$SITE_DIR/faults.js" ] || die "no $SITE_DIR/faults.js — the fault reporter did not build"
[ -f "$SITE_DIR/detect.js" ] || die "no $SITE_DIR/detect.js — the detector did not build"
for icon in favicon.svg favicon-32.png favicon.ico apple-touch-icon.png; do
  [ -f "$SITE_DIR/$icon" ] || die "missing $SITE_DIR/$icon — run: npm run icons"
done

# 🔴 THE GATE READS THE ATTRIBUTE, NOT THE FILE (fixed 22 Sep 2026, at the first deploy).
#
# It was `grep -q 'G-PENDING' "$SITE_DIR/index.html"` — a bare substring search over the whole page —
# and the comment beside the script tag contains the words "reads G-PENDING, which means `npm test`
# cannot pass". So the gate found the placeholder in its OWN EXPLANATION and refused to deploy a site
# whose Analytics id was real. Measured: the only occurrence in the file was inside that comment.
#
# **A check that searches the whole file for a string matches the prose that describes the string.**
# This one reads the attribute it is about, and it fails loudly if the attribute is missing altogether —
# a page with no tag at all must not pass by absence.
grep -q 'data-ga-id="G-PENDING"' "$SITE_DIR/index.html" && die "the Analytics id is still the placeholder"
grep -q 'data-ga-id="G-' "$SITE_DIR/index.html" || die "no Analytics property is wired — the tag has gone"

say "4/6 · has the DNS record been created? (house rule 7a: at deployment, never before)"
if ! dig +short "$HOST" >/dev/null 2>&1 || [ -z "$(dig +short "$HOST" || true)" ]; then
  echo "  The name $HOST does not resolve yet."
  echo "  Create the DNS record NOW, with the deploy — that is the rule, and it is"
  echo "  also the only order in which the certificate can be issued:"
  echo
  echo "    ~/.cloudflare_open.py https://dash.cloudflare.com/"
  echo "    A  $HOST -> 178.128.225.32  (proxied)"
  echo
  die "stopping before anything is published"
fi
echo "  $HOST resolves."

say "5/6 · publish the static site, then the proxy"
if [ "$DRY_RUN" = "--dry-run" ]; then
  echo "  dry run: rsync $SITE_DIR/ → dvs-sites:$REMOTE_DIR/"
  echo "  dry run: wrangler deploy"
  echo "  dry run: report the deploy to Rollbar"
else
  ssh dvs-sites "sudo mkdir -p $REMOTE_DIR"
  rsync -az --delete --rsync-path="sudo rsync" "$SITE_DIR/" "dvs-sites:$REMOTE_DIR/"

  # 🔴 THE CADDY BLOCK MUST BE IN PLACE AND MUST CARRY `no-store` ON THE SHELL,
  # or a returning visitor reads their own cache and a correct deploy looks
  # exactly like no deploy. It also has to import the family's (clean-urls)
  # snippet, so no URL a visitor sees ends in .html.
  ssh dvs-sites "sudo grep -q '$HOST' /etc/caddy/Caddyfile" || {
    echo "  The Caddy block for $HOST is not there yet. Add it — it must import"
    echo "  (clean-urls), must not name www, and must send the shell no-store:"
    echo
    echo "    $HOST {"
    echo "        import (clean-urls)"
    echo "        root * $REMOTE_DIR"
    echo "        @plain not path /static/*"
    echo "        header @plain Cache-Control \"no-store\""
    echo "        file_server"
    echo "    }"
    die "stopping before the reload"
  }
  ssh dvs-sites "sudo caddy validate --config /etc/caddy/Caddyfile && sudo systemctl reload caddy"

  # The proxy. Without it the page loads and every poll fails, because the feed
  # sends no cross-origin header.
  npx --yes wrangler deploy

  # 🔴 THE INTERPRETER IS NAMED ABSOLUTELY, BECAUSE THIS REPO HAS NO `.venv` OF ITS OWN.
  # It read `.venv/bin/python3` — a relative path that exists in the compose repo and not here — so the
  # purge failed with `No such file or directory` on the first deploy. `|| true` kept the deploy running,
  # which is right (a purge is not worth failing a publish over) but it hid the fault in the output.
  "${PURGE_PY:-$HOME/Documents/git/gitlab.com/datavisionstudios/docker-compose-master/.venv/bin/python3}" \
    "$HOME/.cloudflare_purge.py" --all || echo "  (purge skipped — run it by hand if a stale file is suspected)"

  # Rollbar is told WHICH REVISION WENT OUT, so an error is read next to the
  # release that introduced it. 🔴 MEASURED 23 September 2026: this is the one
  # Rollbar call that works before a plan is chosen — `POST /item/` answers 429
  # "This account has been deactivated" while `POST /deploy/` answers 200 with the
  # SAME post_server_item key. It cannot fail the deploy: see tools/report-deploy.mjs.
  node tools/report-deploy.mjs --revision "$(git rev-parse HEAD)" ||
    echo "  (the Rollbar deploy report was skipped — the site is deployed regardless)"
fi

say "6/6 · verify the DEPLOYED page — never trust the push"
if [ "$DRY_RUN" = "--dry-run" ]; then
  echo "  dry run: skipping the live check"
else
  node tools/live-check.mjs "https://$HOST/"
  echo
  echo "  Then, and only then:"
  echo "    1. add this site to the part 5 register   (~/.nodejs_theme_register.py)"
  echo "    2. add it to ~/.seo_audit.py's SITES and ~/.searchconsole_setup.py"
  echo "    3. verify BOTH Search Console properties and submit /sitemap.xml to each"
  echo "    4. add a link to it from nodejavascript.com, in the section it belongs in"
  echo "    5. .venv/bin/python3 ~/.nodejs_compliance.py --save"
fi

say "done"
